### ISSUE TITLE
/opt/mtproto-proxy#   ./mtproxyd marcopolo 6666

### ISSUE THREAD

**Issue by navidx96** [p1ratrulezzz/mtproxy-server-linux#10]
I get an error when I type 
cd /opt/mtproto-proxy
  chmod +x mtproxyd
  ./mtproxyd marcopolo 6666

PHP Parse error:  syntax error, unexpected '}' in /opt/mtproto-proxy/mtproxyd on line 67

**Comment by p1ratrulezzz** [comment]
Try reinstalling, I've fixed the error
