### ISSUE TITLE
Cannot send message but I can do other things

### ISSUE THREAD

**Issue by HirbodBehnam** [p1ratrulezzz/mtproxy-server-linux#11]
Hi I have the problem that I can't send messages. BUT I can download photos, receive messages and (the most hilarious part) I CAN UPLOAD PHOTOS! I'm currently living in Iran and as you know the telegram is banned. Here are some useful info about what happens and my server. 

- The server is located in UK and it's operating system is CentOS 7 and I'm using php 7.
- I've installed it as the same way as _Tutorial for Ubuntu 16.04 Server_ says. But I am running it as the root user.
- My client device is Huawei Mate 10 running android 8 and Telegram v4.8.9(1261)
- There is no error on server side.(Just _Got Connection_, _Closing Fork_ and _Added PID_)

I've noticed that if I reopen the application the message delivers. (This looks interesting for me)
Can anyone give me a hand?

**Comment by p1ratrulezzz** [comment]
Hello. Yes, this is a known problem and on desktop client it works well but on Android with latest clients - not very well, Sometimes messages sent, sometimes not. Try to post the same question on https://github.com/danog/MadelineProto/issues too as it is the main engine of proxy server

**Comment by HirbodBehnam** [comment]
Yeah, I tested my own proxy on telegram-1.2.24.alfa(Portable Version on Windows 10) and that was working fine. So now, as you said, I'm going to open an issue on MadelineProto repository.

**Comment by p1ratrulezzz** [comment]
Yes, thanks. Targeted repo is an actual developer of madeline library and the proxy server itself. This repo is just a copy of daemon files + instructions. And also I don't know if it is an issue of server side or of client side, possibly need to reach the developers of official Telegram client for Android. So sooner or later it will be fixed I believe

**Comment by HirbodBehnam** [comment]
I think it's client side. Because both my PC and my phone were on the same WiFi and the PC worked but my phone didn't(Both were connected to my own VPS). So I assume it's client related. I just assume.

**Comment by p1ratrulezzz** [comment]
You can use this one also https://github.com/alexbers/mtprotoproxy . This one works for me on Android

**Comment by HirbodBehnam** [comment]
Yes. That one is working on android. Thanks for help.

**Comment by sinamiandashti** [comment]
i dont know why the messaging is working but the media is not loading at all @p1ratrulezzz

**Comment by p1ratrulezzz** [comment]
Yes, it still doesn't work and not fixed my developer. Use another server implementation (check readme). i
I recommend to use Java variant as it is easy to use. Preferable version is official version (check link in readme also, there is my tutorial)
