### ISSUE TITLE
invalid user: ‘/opt/mtproto-proxy’

### ISSUE THREAD

**Issue by mohamad171** [p1ratrulezzz/mtproxy-server-linux#12]
hi i install and run mtproxy with that tutorial but when i run it telegram can not connect to this

when i run this command:

  chown /opt/mtproto-proxy mtproxy:mtproxy

got error: chown: invalid user: ‘/opt/mtproto-proxy’

how can i fix this error?

**Comment by p1ratrulezzz** [comment]
You skipped second step in tutorial 


useradd --shell /usr/sbin/nologin -M -u 3000 -o mtproxy


And the correct command is 

chown -R mtproxy:mtproxy /opt/mtproto-proxy

**Comment by mohamad171** [comment]
No , i run this command 
user created.
my passwd file:

mtproxy:x:3000:3000::/home/mtproxy:/usr/sbin/nologin

**Comment by p1ratrulezzz** [comment]
Sorry it was my bad. I've fixed tutorial, the command chown wasn't correct

**Comment by mohamad171** [comment]
Ok thank you 💙
