### ISSUE TITLE
Running it on Cygwin - more like help request

### ISSUE THREAD

**Issue by YaSoC** [p1ratrulezzz/mtproxy-server-linux#2]
It was a bit challengeble to run, but not that much.
Actually server can be started with minor changes to the mtproxyd

The server runs fine, but is available only at local machine.
i believe its caused because its being listening on 0.0.0.0

is there anyone, who has ideas, how to move it to "real" interface?

**Comment by p1ratrulezzz** [comment]
I didn't test this on windows but for attaching it to some interface you just need to edit mtproxyd and set "0.0.0.0" to your public ip address that can be revealed by visiting https://whatismyipaddress.com/

Also check your firewall settings (or disable it for testing at least), the port you use most be open from internal network and from the internet (also check your router, you should forward port 6666 to your machine from the dst-nat)

**Comment by YaSoC** [comment]
Thank you very much. It was so easy.
But, unfortunately, it didn't solve the issue.

I have to investigate further.
